// Pairings — the entire editorial archive lives here as typed data.
//
// To add a new pairing: paste a new object at the TOP of PAIRINGS,
// give it a slug like "20260501-supreme-court", fill in both halves
// to roughly equal word counts, and push.
//
// Voice rules (see CLAUDE.md):
// - Lowercase headlines and body.
// - Both halves equal weight — same word band (±30%), same intensity.
// - No em-dashes. Use commas, en-dashes, or rewrite.
// - Source URLs go in source.url; source.name is the publication.
// - Topic is one of: climate, war, democracy, economy, ai, health,
//   science, culture, rights, other.

export type PairingTopic =
  | "climate"
  | "war"
  | "democracy"
  | "economy"
  | "ai"
  | "health"
  | "science"
  | "culture"
  | "rights"
  | "other";

export type PairingHalf = {
  headline: string;
  body: string;
  source: { name: string; url: string };
  country?: string; // ISO-2 or display label like "global"
  date?: string; // overrides Pairing.date if a half references an older event
};

export type Pairing = {
  slug: string; // YYYYMMDD-keyword, e.g. 20260501-temperature
  date: string; // ISO date, e.g. 2026-05-01
  topic: PairingTopic;
  hard: PairingHalf;
  hopeful: PairingHalf;
  editor_note?: string; // optional one-liner from the editor
  pinned?: boolean; // pinned pairings sit above the timeline
};

// Newest first. The home page reads in this order.
//
// Every pairing here is sourced from real news within ~2 weeks of its
// publication date. URLs verified at insertion time. Editorial voice
// rules in CLAUDE.md.
export const PAIRINGS: Pairing[] = [
  {
    slug: "20260501-pressfreedom-syria",
    date: "2026-05-01",
    topic: "democracy",
    hard: {
      headline: "rsf index records the lowest global press freedom score in twenty-five years.",
      body: "the april 30 reporters without borders index marks the first year more than half of 180 countries fall into the difficult or very serious categories. the share of the world's population living somewhere with good press freedom has dropped from twenty percent to under one percent, leaving seven mostly nordic countries in that band.",
      source: { name: "Al Jazeera", url: "https://www.aljazeera.com/news/2026/4/30/global-press-freedom-falls-to-its-lowest-level-in-25-years" },
      country: "global",
    },
    hopeful: {
      headline: "post-assad syria climbs thirty-six places in the same press freedom ranking.",
      body: "the same april 30 rsf index records the steepest improvement of any country: syria moved up thirty-six places after the fall of the assad government. the index notes the gains remain fragile and uneven, with armed groups still active in the north, but newsrooms shuttered for over a decade have begun publishing again from damascus and aleppo.",
      source: { name: "RSF", url: "https://rsf.org/en/2026-rsf-index-press-freedom-25-year-low" },
      country: "SY",
    },
    editor_note: "same report, two ends of the curve.",
    pinned: true,
  },
  {
    slug: "20260430-aifirings-aidrugs",
    date: "2026-04-30",
    topic: "ai",
    hard: {
      headline: "tech sector sheds more than forty thousand jobs in april alone.",
      body: "oracle cut roughly thirty thousand roles, meta about eight thousand, microsoft offered voluntary exits to 8,750, and snap let go sixteen percent of its global staff. cumulative q1-to-april losses passed 92,000. industry trackers attribute close to half of q1 cuts to ai and workflow automation. tech-sector unemployment is the highest since the dot-com bust.",
      source: { name: "Business Today", url: "https://www.businesstoday.in/technology/story/tech-layoffs-2026-nearly-40000-jobs-lost-in-april-amid-changing-ai-priorities-528282-2026-04-30" },
      country: "global",
    },
    hopeful: {
      headline: "isomorphic labs prepares first human trials of fully ai-designed drug candidates.",
      body: "the deepmind spinoff confirmed on april 25 that molecules generated by its iso drug design engine are entering clinical testing for cancer and immune-system disease. partnerships with eli lilly and novartis total around three billion dollars. the company says its design engine is roughly twice as accurate as alphafold 3 at predicting how proteins bind drugs.",
      source: { name: "The News (Reuters wire)", url: "https://www.thenews.com.pk/latest/1400311-ai-drug-breakthrough-google-deepmind-spinoff-isomorphic-labs-begins-human-trials" },
      country: "GB",
    },
    editor_note: "the same technology displacing one workforce is being pointed at a disease that kills ten million a year.",
  },
  {
    slug: "20260429-dnipro-solar",
    date: "2026-04-29",
    topic: "war",
    hard: {
      headline: "russian strike on dnipro kills ten and injures sixty-seven across eight regions.",
      body: "the april 25 assault used 47 missiles and 619 drones over more than twenty hours. eight of the dead were in dnipro, where a four-story residential building and industrial sites were hit. ukrainian air defenses intercepted 580 drones and 30 missiles. kharkiv, chernihiv, sumy, odesa, and kyiv oblast also took damage.",
      source: { name: "Kyiv Independent", url: "https://kyivindependent.com/russian-attack-april-25/" },
      country: "UA",
    },
    hopeful: {
      headline: "iea logs 605 gigawatts of new solar capacity added worldwide in 2025.",
      body: "the agency's april 21 global energy review records the first year solar additions cleared 600 gigawatts, up about 12 percent year on year. thirty countries each installed more than one gigawatt. solar generation grew 600 terawatt-hours, the largest single-year jump from any source outside post-crisis rebounds, and met more than a quarter of global demand growth.",
      source: { name: "IEA", url: "https://www.iea.org/reports/global-energy-review-2026/technology-solar-pv-and-wind" },
      country: "global",
    },
  },
  {
    slug: "20260428-elfasher-malaria",
    date: "2026-04-28",
    topic: "war",
    hard: {
      headline: "sudan doctors network counts 1,470 civilians held in el fasher detention sites.",
      body: "the network's april 27 dispatch lists 1,470 civilians, 907 military personnel, and 20 doctors held in shalla prison, a children's hospital, and cargo containers across el fasher. the group reports cholera since february, field executions, and ethnically motivated killings under rsf control of the city.",
      source: { name: "Al Jazeera", url: "https://www.aljazeera.com/news/2026/4/27/thousands-reportedly-held-by-paramilitary-rsf-in-sudans-el-fasher" },
      country: "SD",
    },
    hopeful: {
      headline: "gavi reports 52 million malaria vaccine doses delivered across 25 african countries.",
      body: "the april 24 update from gavi covers rollouts since 2023, with nine of the ten highest-burden countries now vaccinating at scale. burkina faso recorded a 32 percent drop in reported malaria cases between 2024 and 2025 and roughly halved malaria deaths in children, alongside 26.6 million dollars in household healthcare savings.",
      source: { name: "Gavi", url: "https://www.gavi.org/news/media-room/africas-routine-vaccine-systems-deliver-gains-against-cancer-and-malaria-funding" },
      country: "global",
    },
    editor_note: "africa to africa. the same continent holds both stories in the same week.",
  },
  {
    slug: "20260427-heatwave-ozone",
    date: "2026-04-27",
    topic: "climate",
    hard: {
      headline: "india's heatwave arrives weeks early as banda hits 47.4 degrees in april.",
      body: "the india meteorological department logged 47.4 degrees celsius at banda in uttar pradesh on april 25, the highest reading nationally this year. six cities crossed 46 degrees the same week. imd's april-to-june outlook forecasts above-normal heatwave days across east, central, and northwest india and the southeastern peninsula.",
      source: { name: "India Meteorological Department", url: "https://mausam.imd.gov.in/pdfs/heatcolduser/heat_extended.pdf" },
      country: "IN",
    },
    hopeful: {
      headline: "noaa and nasa rank the 2025 antarctic ozone hole as the fifth smallest since 1992.",
      body: "the joint assessment confirms the long-term recovery trend set in motion by the montreal protocol. the 2025 hole closed on december 1, the earliest since 2019. ozone-depleting substances over antarctica have fallen about a third from their year-2000 peak. full recovery to 1980 values remains projected for around 2066 over the south pole.",
      source: { name: "NOAA", url: "https://www.noaa.gov/news-release/noaa-nasa-2025-ozone-hole-is-5th-smallest-since-1992" },
      country: "global",
    },
    editor_note: "two atmospheric stories. one we are still writing badly, one we have been quietly fixing for forty years.",
  },
  {
    slug: "20260426-victoryday-malaria",
    date: "2026-04-26",
    topic: "war",
    hard: {
      headline: "putin offers a one-day victory parade truce; kyiv asks for thirty.",
      body: "after an april 29 call with donald trump, the kremlin floated a unilateral pause around the may 9 moscow parade. zelensky on april 30 countered with a long-term, guaranteed ceasefire, asking whether the offer meant 'a few hours of security for a parade in moscow, or something more.' negotiations have been stalled for over two months.",
      source: { name: "Kyiv Independent", url: "https://kyivindependent.com/ukraine-proposes-long-term-ceasefire-after-putin-floats-victory-day-truce/" },
      country: "UA",
    },
    hopeful: {
      headline: "world malaria day marks 47 countries now certified malaria-free.",
      body: "the who's april 25 update lists 47 countries with malaria-free certification and 37 reporting fewer than a thousand cases in 2024. roughly ten million children a year are now reached by routine malaria immunization across the 25 rollout countries. the campaign theme this year reads: 'driven to end malaria. now we can. now we must.'",
      source: { name: "WHO", url: "https://www.who.int/campaigns/world-malaria-day/2026" },
      country: "global",
    },
  },
  {
    slug: "20260425-afghanwomen-amazon",
    date: "2026-04-25",
    topic: "rights",
    hard: {
      headline: "unicef projects afghanistan will lose 25,000 women teachers and health workers by 2030.",
      body: "the april 27 analysis records female civil-service representation falling from 21 to 17.7 percent between 2023 and 2025. an estimated 3.8 million girls aged 7 to 18 were out of school in 2024. the cost of current decrees is put at 84 million dollars a year in lost output, with more than two million girls projected out of secondary school by 2030.",
      source: { name: "UN News", url: "https://news.un.org/en/story/2026/04/1167389" },
      country: "AF",
    },
    hopeful: {
      headline: "brazilian amazon deforestation falls to its lowest five-month level since 2014.",
      body: "inpe's prodes alerts logged 1,325 square kilometers of clearing between august 2025 and january 2026, down from 2,050 in the same period a year earlier. environment minister marina silva said seventy of eighty-one priority municipalities have joined federal enforcement programs. the trailing twelve-month figure also sits at the lowest since 2014.",
      source: { name: "Mongabay", url: "https://news.mongabay.com/2026/02/amazon-deforestation-on-pace-to-be-the-lowest-on-record-says-brazil/" },
      country: "BR",
    },
  },
  {
    slug: "20260423-khalil-deafness",
    date: "2026-04-23",
    topic: "health",
    hard: {
      headline: "lebanese journalist amal khalil dies under rubble in southern lebanon as medics are blocked from reaching her.",
      body: "the al-akhbar correspondent had taken shelter in a building that was then directly struck on april 22. cpj said the failure to allow medical access in time may constitute a war crime. it brings to fifteen the journalists and media workers killed by israel in lebanon since october 2023.",
      source: { name: "Committee to Protect Journalists", url: "https://cpj.org/2026/04/cpj-calls-for-urgent-international-investigation-into-israels-killing-of-lebanese-journalist-amal-khalil/" },
      country: "LB",
    },
    hopeful: {
      headline: "the fda approves the first gene therapy for inherited deafness, with eighty percent of trial children gaining hearing.",
      body: "approved april 23, otarmeni delivers a working copy of the otof gene to children born without the ear-to-brain messenger protein. of twenty trial participants, sixteen gained hearing; five reached essentially normal range. regeneron has committed to providing the therapy at no cost to patients in the united states.",
      source: { name: "CNN", url: "https://edition.cnn.com/2026/04/23/health/fda-gene-therapy-inherited-deafness-regeneron" },
      country: "global",
    },
  },
  {
    slug: "20260421-ice-mars",
    date: "2026-04-21",
    topic: "science",
    hard: {
      headline: "ice custody deaths reach a record seventeen in the current fiscal year.",
      body: "the latest, twenty-seven-year-old aled carbonell-betancourt of cuba, was found dead in detention and ruled a suicide. the figure surpasses every annual total in more than two decades of recorded ice deaths. on april 21, sixty-two military veterans were arrested at the cannon house office building protesting the iran war.",
      source: { name: "Democracy Now!", url: "https://www.democracynow.org/2026/4/21/headlines" },
      country: "US",
    },
    hopeful: {
      headline: "curiosity finds the largest organic molecules ever detected on mars, including dna-precursor compounds.",
      body: "results published april 21 in nature communications describe more than twenty organics, among them benzothiophene and nitrogen-bearing rings, drilled from clay-rich rock in glen torridon. some may have been preserved for three and a half billion years. their origin, biological, geological, or meteoritic, remains undetermined.",
      source: { name: "Phys.org", url: "https://phys.org/news/2026-04-mars-rover-compounds.html" },
      country: "global",
    },
  },
  {
    slug: "20260420-teotihuacan-goldman",
    date: "2026-04-20",
    topic: "rights",
    hard: {
      headline: "a gunman opens fire from atop the pyramid of the moon, killing one tourist and wounding thirteen.",
      body: "julio césar jasso ramírez, twenty-seven, fired roughly thirty rounds into the crowd at teotihuacán shortly before noon on april 20, then took his own life. a canadian woman was killed; the wounded included six americans, three colombians, two brazilians, a russian and another canadian. notes referenced the 1999 columbine massacre.",
      source: { name: "CBS News", url: "https://www.cbsnews.com/news/mexico-shooting-teotihuacan-pyramids/" },
      country: "MX",
    },
    hopeful: {
      headline: "the goldman environmental prize names six women laureates, a first in the award's thirty-seven-year history.",
      body: "honored in san francisco on april 20: iroro tanshi for protecting nigeria's short-tailed roundleaf bat, sarah finch for the uk supreme court ruling on downstream emissions, theonila roka matbob for the panguna mine accord, alannah hurley for the pebble mine veto, yuvelis morales blanco for the colombian fracking ruling, and borim kim for asia's first youth climate verdict.",
      source: { name: "Mongabay", url: "https://news.mongabay.com/2026/04/meet-the-2026-goldman-environmental-prize-winners/" },
      country: "global",
    },
  },
  {
    slug: "20260419-shreveport-stratford",
    date: "2026-04-19",
    topic: "culture",
    hard: {
      headline: "eight children, ages three to eleven, are killed by their father across three shreveport homes.",
      body: "shamar elkins, thirty-one, shot seven of his biological children and one nephew in the early hours of april 19, then was killed by police after a pursuit. it is the deadliest single-day mass shooting in louisiana history and the deadliest in the united states since january 2024. two women were also seriously wounded.",
      source: { name: "RTE", url: "https://www.rte.ie/news/us/2026/0420/1569102-louisiana-shooting/" },
      country: "US",
    },
    hopeful: {
      headline: "the v&a east opens in stratford with a 125-year retrospective of black british music.",
      body: "the museum's first-ever exhibition, the music is black: a british story, opened to the public on april 18, tracing lovers rock, two tone, jungle, trip hop, grime and beyond across more than two hundred objects. joan armatrading's childhood guitar sits beside samuel coleridge-taylor's conducting batons from the early 1900s.",
      source: { name: "V&A", url: "https://www.vam.ac.uk/exhibitions/the-music-is-black-a-british-story" },
      country: "GB",
    },
  },
  {
    slug: "20260418-peacekeeper-prize",
    date: "2026-04-18",
    topic: "science",
    hard: {
      headline: "a french peacekeeper is killed in southern lebanon, one day into a fragile ceasefire.",
      body: "staff sergeant florian montorio, of the 17th parachute engineer regiment, was clearing an isolated road in ghandouriyeh when small-arms fire hit his unifil disposal team on april 18. macron and unifil attribute the ambush to hezbollah, which denies it. a wounded corporal would die in paris four days later.",
      source: { name: "Al Jazeera", url: "https://www.aljazeera.com/news/2026/4/18/french-soldier-serving-with-unifil-killed-in-lebanon-attack" },
      country: "LB",
    },
    hopeful: {
      headline: "the breakthrough prize names laureates whose work has already turned three incurable diseases into treatable ones.",
      body: "announced in los angeles on april 18, the 2026 breakthrough prize honors gene therapies for inherited blindness, sickle cell disease, and beta-thalassemia. six prizes of three million dollars each were awarded across life sciences, physics, and mathematics, bringing the program's fifteen-year total above 340 million.",
      source: { name: "Breakthrough Prize", url: "https://breakthroughprize.org/News/98" },
      country: "global",
    },
  },
];

export function getPairing(slug: string): Pairing | undefined {
  return PAIRINGS.find((p) => p.slug === slug);
}

export function allSlugs(): string[] {
  return PAIRINGS.map((p) => p.slug);
}

export function pairingsByTopic(topic: PairingTopic): Pairing[] {
  return PAIRINGS.filter((p) => p.topic === topic);
}

export function pinnedFirst(): Pairing[] {
  const pinned = PAIRINGS.filter((p) => p.pinned);
  const rest = PAIRINGS.filter((p) => !p.pinned);
  return [...pinned, ...rest];
}

// counts used by /stats and the homepage stats strip. computed at
// build-time so they update on every deploy without a roundtrip.
export function computeStats() {
  const total = PAIRINGS.length;
  const countries = new Set<string>();
  const sources = new Set<string>();
  const topics = new Set<string>();
  let hardCountries = 0;
  let hopefulCountries = 0;
  for (const p of PAIRINGS) {
    if (p.hard.country && p.hard.country !== "global") {
      countries.add(p.hard.country);
      hardCountries++;
    }
    if (p.hopeful.country && p.hopeful.country !== "global") {
      countries.add(p.hopeful.country);
      hopefulCountries++;
    }
    sources.add(p.hard.source.name);
    sources.add(p.hopeful.source.name);
    topics.add(p.topic);
  }
  // earliest pairing date — "since X" copy
  const dates = PAIRINGS.map((p) => p.date).sort();
  return {
    total,
    countries: countries.size,
    sources: sources.size,
    topics: topics.size,
    hardCountries,
    hopefulCountries,
    earliest: dates[0],
    latest: dates[dates.length - 1],
  };
}

export function pickRandomSlug(): string {
  if (PAIRINGS.length === 0) return "";
  // intentionally not deterministic — this is the "stumble" feature
  return PAIRINGS[Math.floor(Math.random() * PAIRINGS.length)].slug;
}

export const TOPIC_LABEL: Record<PairingTopic, string> = {
  climate: "climate & environment",
  war: "conflict & peace",
  democracy: "democracy",
  economy: "economy & work",
  ai: "ai & technology",
  health: "health",
  science: "science",
  culture: "culture",
  rights: "rights",
  other: "other",
};
